### ISSUE TITLE
Part 1 Step 12 Error requesting Test Results

### ISSUE THREAD

**Issue by gumbelmj** [battjt/j1939-84#565]
From Eric:

```
End Step 1.11. DM21: Diagnostic readiness 2
 
Start Step 1.12. DM7/DM30: Command Non-continuously Monitored Test/Scaled Test Results
 
// Queries appear to be sequenced as reported in DM24
(Supporting Scaled Test Results) [
  SPN 102 - Engine Intake Manifold #1 Pressure
  SPN 157 - Engine Fuel 1 Injector Metering Rail 1 Pressure
  SPN 651 - Engine Fuel 1 Injector Cylinder 1
  SPN 652 - Engine Fuel 1 Injector Cylinder 2
// There is a mixup in DM7 queries for SP 157 and 651
 
 
08:39:20.5313 Sending DM7 for DM30 to Engine #1 (0) for SPN 102
08:39:20.5513 18E300F9 [8] F7 66 00 1F FF FF FF FF (TX)
08:39:20.5572 18A4F900 [36] F7 66 00 10 84 01 00 FB FF FF FF FF F7 66 00 12 84 01 00 FB FF FF FF FF F7 66 00 0A 84 01 00 FB FF FF FF FF
DM30 from 0: [
  SPN 102 FMI 16 (SLOT 388) Result: Test Not Complete.
  SPN 102 FMI 18 (SLOT 388) Result: Test Not Complete.
  SPN 102 FMI 10 (SLOT 388) Result: Test Not Complete.
]
 
 
08:39:20.6360 Sending DM7 for DM30 to Engine #1 (0) for SPN 157
 
FAIL: 6.1.12.1.a - No test result for Supported SPN 157 from Engine #1 (0)
// Query supporting this failure for SPN 157 message is not in the log
// Then the query for SPN 651 is sent using SPN 9D or 157
 
08:39:20.7447 Sending DM7 for DM30 to Engine #1 (0) for SPN 651
08:39:20.7472 18E300F9 [8] F7 9D 00 1F FF FF FF FF (TX)
08:39:20.7487 18A4F900 [48] F7 9D 00 10 82 01 00 FB FF FF FF FF F7 9D 00 12 82 01 00 FB FF FF FF FF F7 9D 00 07 82 01 C1 10 7C 15 00 00 F7 9D 00 07 82 01 C1 10 6C DC C4 09
DM30 from 0: [
  SPN 157 FMI 16 (SLOT 386) Result: Test Not Complete.
  SPN 157 FMI 18 (SLOT 386) Result: Test Not Complete.
  SPN 157 FMI 7 (SLOT 386) Result: Test Passed. Min: -40,000, Value: 2,890, Max: 15,000 kPa
  SPN 157 FMI 7 (SLOT 386) Result: Test Passed. Min: -15,000, Value: 2,890, Max: 524,280 kPa
]
 
FAIL: 6.1.12.1.a - No test result for Supported SPN 651 from Engine #1 (0)
WARN: 6.1.12.1.d - Engine #1 (0) returned duplicate test results for SPN 157 FMI 7
// DM7 for SPN 651 is missing from log.
// SPN 157 FMI 7 message should precede query and messages for missing DM7 SP 651 query
 
 
08:39:20.7966 Sending DM7 for DM30 to Engine #1 (0) for SPN 652
08:39:20.8022 18E300F9 [8] F7 8C 02 1F FF FF FF FF (TX)
08:39:20.8036 18A4F900 [12] F7 8C 02 07 00 01 00 FB FF FF FF FF
DM30 from 0: SPN 652 FMI 7 (SLOT 256) Result: Test Not Complete.



The 0.1.12 results appeared to be correct as:
 
Start Step 1.12. DM7/DM30: Command Non-continuously Monitored Test/Scaled Test Results
 
08:27:39.1634 Sending DM7 for DM30 to Engine #1 (0) for SPN 102
08:27:39.2325 18E300F9 [8] F7 66 00 1F FF FF FF FF (TX)
08:27:39.1724 18A4F900 [36] F7 66 00 10 84 01 00 FB FF FF FF FF F7 66 00 12 84 01 00 FB FF FF FF FF F7 66 00 0A 84 01 00 FB FF FF FF FF
DM30 from 0: [
  SPN 102 FMI 16 (SLOT 388) Result: Test Not Complete.
  SPN 102 FMI 18 (SLOT 388) Result: Test Not Complete.
  SPN 102 FMI 10 (SLOT 388) Result: Test Not Complete.
]
 
08:27:39.2022 Sending DM7 for DM30 to Engine #1 (0) for SPN 157
08:27:39.2735 18E300F9 [8] F7 9D 00 1F FF FF FF FF (TX)
08:27:39.2142 18A4F900 [48] F7 9D 00 10 82 01 00 FB FF FF FF FF F7 9D 00 12 82 01 00 FB FF FF FF FF F7 9D 00 07 82 01 DF 10 7C 15 00 00 F7 9D 00 07 82 01 DF 10 6C DC C4 09
DM30 from 0: [
  SPN 157 FMI 16 (SLOT 386) Result: Test Not Complete.
  SPN 157 FMI 18 (SLOT 386) Result: Test Not Complete.
  SPN 157 FMI 7 (SLOT 386) Result: Test Passed. Min: -40,000, Value: 3,190, Max: 15,000 kPa
  SPN 157 FMI 7 (SLOT 386) Result: Test Passed. Min: -15,000, Value: 3,190, Max: 524,280 kPa
]
 
FAIL: 6.1.12.1.b - Test result for SPN 157 FMI 7 from Engine #1 (0) does not report the test result/min test limit/max test limit initialized properly
FAIL: 6.1.12.1.b - Test result for SPN 157 FMI 7 from Engine #1 (0) does not report the test result/min test limit/max test limit initialized properly
WARN: 6.1.12.1.d - Engine #1 (0) returned duplicate test results for SPN 157 FMI 7
08:27:39.2460 Sending DM7 for DM30 to Engine #1 (0) for SPN 651
08:27:39.3170 18E300F9 [8] F7 8B 02 1F FF FF FF FF (TX)
08:27:39.2529 18A4F900 [12] F7 8B 02 07 00 01 00 FB FF FF FF FF
DM30 from 0: SPN 651 FMI 7 (SLOT 256) Result: Test Not Complete.
 
08:27:39.2639 Sending DM7 for DM30 to Engine #1 (0) for SPN 652
08:27:39.3330 18E300F9 [8] F7 8C 02 1F FF FF FF FF (TX)
08:27:39.2728 18A4F900 [12] F7 8C 02 07 00 01 00 FB FF FF FF FF
DM30 from 0: SPN 652 FMI 7 (SLOT 256) Result: Test Not Complete.
```

**Comment by gumbelmj** [comment]
In the logs:
```
2021-02-12 08:39:20.743 SEVERE org.etools.j1939_84.bus.j1939.J1939 severe Error requesting DS packet
org.etools.j1939_84.bus.BusException: Failed to send: 18E300F9 [8] F7 9D 00 1F FF FF FF FF (TX)
	at org.etools.j1939_84.bus.RP1210Bus.lambda$send$3(RP1210Bus.java:298)
	at java.base/java.util.Optional.orElseThrow(Unknown Source)
	at org.etools.j1939_84.bus.RP1210Bus.send(RP1210Bus.java:298)
	at org.etools.j1939_84.bus.j1939.J1939TP.send(J1939TP.java:396)
	at org.etools.j1939_84.bus.j1939.J1939.requestDM7(J1939.java:498)
	at org.etools.j1939_84.modules.DiagnosticMessageModule.getDM30Packets(DiagnosticMessageModule.java:209)
	at org.etools.j1939_84.controllers.part01.Part01Step12Controller.run(Part01Step12Controller.java:99)
	at org.etools.j1939_84.controllers.Controller.lambda$getRunnable$0(Controller.java:383)
	at org.etools.j1939_84.controllers.Controller.run(Controller.java:451)
	at org.etools.j1939_84.controllers.PartController.run(PartController.java:67)
	at org.etools.j1939_84.controllers.Controller.lambda$getRunnable$0(Controller.java:383)
	at org.etools.j1939_84.controllers.Controller.run(Controller.java:451)
	at org.etools.j1939_84.controllers.OverallController.run(OverallController.java:97)
	at org.etools.j1939_84.controllers.Controller.lambda$getRunnable$0(Controller.java:383)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by gumbelmj** [comment]
@battjt ,

Issue traces back to this code in the `RP1210Bus` Class:

```
 @Override
    public Packet send(Packet tx) throws BusException {
        byte[] data = encode(tx);
        try (Stream<Packet> stream = read(100, TimeUnit.MILLISECONDS)) {
            // rp1210 libraries may not be thread safe
            short rtn = exec.submit(() -> rp1210Library.RP1210_SendMessage(clientId,
                    data,
                    (short) data.length,
                    NOTIFICATION_NONE,
                    BLOCKING_NONE)).get();
            verify(rtn);
            final int id = tx.getId(0xFFFF);
            final int source = tx.getSource();
            return stream
                    .filter(rx -> rx.isTransmitted() && id == rx.getId(0xFFFF) && rx.getSource() == source)
                    .findFirst()
                    .orElseThrow(() -> new BusException("Failed to send: " + tx));
        } catch (Throwable e) {
            throw e instanceof BusException ? (BusException) e : new BusException("Failed to send: " + tx, e);
        }
    }
```

It appears the adapter failed to send the message.  But then actually sent it?

**Comment by gumbelmj** [comment]
I think the read timeout might be too aggressive.  There was 108.7 ms between the logging of the first request for SPN 157 and the second for SPN 651.  But it appears the request for SPN 157 was actually sent.  As the results we interpreted for the request for SPN 651.

@battjt  where did 100 ms timeout come from?

**Comment by ericthomasswenson** [comment]
Based on Joe’s oral explanation, an increased timeout should be more forgiving.
Given the relative stability of test results from this ISL engine in the past,
Let’s roll with the increased time.  I intuitively suggested 10%.
