### ISSUE TITLE
String index out of range

### ISSUE THREAD

**Issue by battjt** [battjt/j1939-84#88]
java.lang.StringIndexOutOfBoundsException: String index out of range: 13
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at java.base/java.lang.String.charAt(String.java:693)
	at org.etools.j1939_84.controllers.part1.Step06Controller.run(Step06Controller.java:77)
	at org.etools.j1939_84.controllers.Controller.lambda$0(Controller.java:463)
	at org.etools.j1939_84.controllers.Controller.run(Controller.java:540)
	at org.etools.j1939_84.controllers.part1.Part01Controller.executeStepTest(Part01Controller.java:133)
	at org.etools.j1939_84.controllers.part1.Part01Controller.executeStep(Part01Controller.java:125)
	at org.etools.j1939_84.controllers.part1.Part01Controller.run(Part01Controller.java:156)
	at org.etools.j1939_84.controllers.Controller.lambda$0(Controller.java:463)

**Comment by mmschaefer** [comment]
Fixed in merge #88
